[package]
name = "equation-maker"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
miette = { version = "7.6.0", features = ["fancy"] }
regex = "1.11.1"
